sudo: required
dist: trusty
language: bash

jobs:
  include:
    - stage: build image
      script:
        - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
            TAG=v`date +"%Y%m%d"`;
            docker run --rm --privileged multiarch/qemu-user-static:register --reset;
            docker build . -t colachen/dnscrypt-rpi:latest -t colachen/dnscrypt-rpi:$TAG;
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin;
            docker push colachen/dnscrypt-rpi:$TAG;
            docker push colachen/dnscrypt-rpi:latest;
          fi

    - stage: test image
      script:
        - docker run --rm --privileged multiarch/qemu-user-static:register --reset
        - docker run --rm colachen/dnscrypt-rpi -version